config/routes.rb
Rails.application.routes.draw do
  get 'about/index'

  root 'welcome#index'

  resources :welcome, only: [:create]
  resources :user_sessions

  resources :drivers do
    resources :appointments
  end

  resources :users do
    resources :appointments
    resources :grades, only: [:create]
  end
  resources :cohorts do
    resources :exams
  end

  resources :questions
  resources :attacheds, only: [:create, :destroy]
  resources :answers
  resources :scantrons, only: [:create, :update]

  get 'redlight' => 'games#redlight', :as => :redlight
  get 'login' => 'user_sessions#new', :as => :login
  get 'logout' => 'user_sessions#destroy', :as => :logout

end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :appointments
  has_many :scantrons
  has_many :drivers, through: :appointments
  belongs_to :cohort
  authenticates_with_sorcery!

  validates :password, length: { minimum: 3 }, if: -> { new_record? || changes["password"] }
  validates :password, confirmation: true, if: -> { new_record? || changes["password"] }
  validates :password_confirmation, presence: true, if: -> { new_record? || changes["password"] }

  validates :email, uniqueness: true

  ROLES = %i[admin student driving_instructor]

  def self.instructor_id(name)
    u = User.where(name: name).first
    u.id
  end

  def completed_any_test?
    Scantron.any_test_complete?(self.id)
  end

  def self.any_user_completed_test?
    User.all.each { |user|
      return true if Scantron.any_test_complete?(user.id)
    }
    return false
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  require 'gruff'
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  skip_before_action :require_login, only: [:index, :new, :create]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(current_user.id)
    exam_labels = {}

    g = Gruff::Bar.new
    g.title = "Exam Results for #{current_user.name}"

    test_results = []
    current_user.scantrons.each_with_index { |scantron, index|
      test_results << scantron.convert_to_percent if scantron.result != nil
      exam_labels[index] = Exam.get_exam_by_scantron(scantron).name unless scantron.game_name != nil
    }
    g.data current_user.name.to_sym, test_results

    g.labels = exam_labels
    g.marker_count = 1
    # g.write('app/assets/images/userexamresults.png')
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        auto_login(@user)
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.js
        # format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation, :role, :cohort_id)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name%><br>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>

  <div class="field">
   <%= f.label :password %><br />
   <%= f.password_field :password %>
  </div>

  <div class="field">
   <%= f.label :password_confirmation %><br />
   <%= f.password_field :password_confirmation %>
  </div>

  <%= f.collection_select(:role, User::ROLES, :to_s, lambda{|i| i.to_s.humanize}) %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/_user.html.erb
<div class="individual-student">
  <%= user.name %>
</div>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Listing Users</h1>

<table>
  <thead>
    <tr>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <%= user.email %>
        <!-- <td><%= link_to 'Show', user %></td> -->
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<!-- <%= link_to 'New User', new_user_path %> -->

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<h1>
  <%= @user.name %><br>
</h1>
<br>
<br>
<div class="user-link-images">
  <div class="user-book-appointment">
    <h4>BOOK AN APPOINTMENT</h4>
    <%= link_to image_tag("calendar.svg", width: 100, height: 100), new_user_appointment_path(@user.id) %>
  </div>
  <br>
  <div class="user-do-test">
    <h4>TESTS</h4>
    <%= link_to image_tag("Test-paper-icon.png", width: 100, height: 100), cohorts_path %>
  </div>
</div>
<br>

<div class="user-scantron-results">
  <% if @user.scantrons.any? %>
  
  <% end %>
</div>
<br>


<div class="usersfooter">
  <%= link_to 'Edit', edit_user_path(@user) %> |
  <%= link_to 'Back', users_path %>
</div>

app/views/users/update.js.erb
$('.student-container').append('<%= j (render @user) %>')