config/routes.rb
Rails.application.routes.draw do
  get 'about/index'

  root 'welcome#index'

  resources :welcome, only: [:create]
  resources :user_sessions

  resources :drivers do
    resources :appointments
  end

  resources :users do
    resources :appointments
    resources :grades, only: [:create]
  end
  resources :cohorts do
    resources :exams
  end

  resources :questions
  resources :attacheds, only: [:create, :destroy]
  resources :answers
  resources :scantrons, only: [:create, :update]

  get 'redlight' => 'games#redlight', :as => :redlight
  get 'login' => 'user_sessions#new', :as => :login
  get 'logout' => 'user_sessions#destroy', :as => :logout

end

app/models/exam.rb
class Exam < ActiveRecord::Base
  validates :name, :presence => true
  validates :cohort_id, :presence => true

  belongs_to :cohort
  has_many :attacheds
  has_many :questions, :through => :attacheds
  has_many :scantrons

  def average_grade
    if self.scantron.any?
      total_score = 0
      total_questions = 0
      running_score = []

      self.scantrons.each do |scantron|
        if scantron.answers.any?
          scantron.answers.each do |answer|
            total_questions += 1
            if answer.correct == true
              total_score += 1
            end
          end
        running_score << total_score/total_questions
        end
      end

      running_score != 0 ? "#{((running_score.sum / running_score.length)*100)}%" : ""
    end
  end

  def self.get_exam_by_scantron(scantron)
    Exam.where(id: scantron.exam_id).first
  end

end

app/controllers/exams_controller.rb
class ExamsController < ApplicationController
  before_action :load_cohort, only: [:show, :destroy, :edit, :new, :create]
  before_action :load_exam, only: [:show]

  def index
    @exams = @cohort.exams
  end

  def new
    @exam = @cohort.exams.build
  end

  def show
    # For creating an exam
    @attachedquestion = Attached.new
    @attachedquestions = @exam.questions
    @unusedquestions = @exam.unused_questions

    # For doing an exam
    if Scantron.where(user_id: current_user).where(exam_id: @exam.id).first
      @scantron = Scantron.where(user_id: current_user.id).where(exam_id: @exam.id).first
    else
      @scantron = Scantron.create(user_id: current_user.id, exam_id: @exam.id)
    end

    @answers = @scantron.answers
    @categories = Category.all
  end

  def edit
  end

  def update
    if @exam.update_attributes(exam_params)
      redirect_to exam_path(@exam)
    end
  end

  def create
    @exam = @cohort.exams.build(exam_params)

    if @exam.save
      redirect_to cohort_path(@cohort)
    else
      render :new
    end
  end

  def destroy
    @exam.destroy
    redirect_to cohorts_path
  end

  private

  def exam_params
    params.require(:exam).permit(:name, :cohort_id)
  end

  def load_cohort
    @cohort = Cohort.find(params[:cohort_id])
  end

  def load_exam
    @exam = Exam.find(params[:id])
  end
end

app/helpers/exams_helper.rb
module ExamsHelper
end

app/views/exams/_attachedquestion.html.erb
<div class="attached-question-class">
  <h3>
    <% if index != nil%>
      <%= index + 1 %>)
    <% end %>
    <%= attachedquestion.content %>
  </h3>
  <% if attachedquestion.choices.any? %>
    <ul>
      <% attachedquestion.choices.each do |choice| %>
        <% choice.correct ? color_class = "correct" : color_class = "incorrect"%>
        <li class="<%= color_class %>"><%= choice.content %></li>
      <% end %>
    </ul>
  <% end %>
</div>

app/views/exams/_form.html.erb
<%= form_for [@cohort, @exam] do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.submit  %>
<% end %>

app/views/exams/index.html.erb
<% if @exams.any? %>
  <% @exams.each do |exam| %>
    <%= link_to exam.name, cohort_exam_path(exam) %>
  <% end %>
<% end %>

<div>Create New Exam</div>

<%= render 'form' %>

app/views/exams/new.html.erb
<%= render 'form' %>

app/views/exams/show.html.erb
<h1><%= @exam.name %> Test</h1>

<% unless current_user.role == "student" %>
<div class="attachedquestionlist">
  <% if @attachedquestions.any? %>
    <h3>List of Questions on Exam</h3>
    <% @attachedquestions.each_with_index do |question, index| %>
      <%= render partial: 'attachedquestion', locals: {attachedquestion: question, index: index}%>
    <% end %>
  <% end %>
</div>

<%= form_for @attachedquestion, remote: true do |f| %>
  <%= f.hidden_field(:exam_id, :value => @exam.id) %>
  <%= f.text_field :question_id %>
  <%= f.submit %>
<% end %>

<br>

<div class="flipq showquestions">
  <span class="display-question show-question-list">SHOW QUESTIONS</span>
  <span class="hide-question show-question-list">HIDE QUESTIONS</span>
</div>

<div class="list-of-questions">
  <div>
    <%= link_to "Add New Question", new_question_path %>
  </div>

  <% @categories.each do |category| %>
    <% if category.questions.any? %>
      <div class="examcategories">
        <h3><%= category.name %></h3>
          <% ids_of_unused_questions = @unusedquestions.map(&:id) %>
          <% unused_questions_in_category = category.questions.where(id: ids_of_unused_questions) %>
        <%= render partial: 'questions/form', collection: unused_questions_in_category, as: :question%>
      </div>
    <% end %>
  <% end %>
</div>
<% end %>

<br>
<% if current_user && @scantron.result == nil %>
  <% @attachedquestions.each do |question| %>
    <div class="questioncontainer">
      <!-- Hidden form for submitting an answer  -->
      <%= form_for Answer.new, :html => {:class => 'realanswerform'}, remote: true do |f| %>
        <%= f.hidden_field(:scantron_id, :value => @scantron.id) %>
        <%= f.hidden_field(:question_id, :value => question.id) %>
        <%= f.hidden_field(:choice_id, :class => 'realanswerchoice') %>
        <%= f.hidden_field(:correct, :value => false, :class => 'realanswercorrect', :id => question.id) %>
        <%= f.submit :class => 'realanswersubmit' %>
      <% end %>
      <!-- Visible div to click choices  -->
      <p class="questioncontent"><%= question.content %></p>
      <% question.choices.each do |choice| %>
        <% choice.correct ? choicelisting = 1 : choicelisting = 0 %>
        <div class="choicecontainer" id="choicecontainer" data-spoon="<%=choicelisting%>" data-qnum ="<%= question.id %>" data-cnum="<%= choice.id %>">
          <%= choice.content %>
        </div>
      <% end %>

    </div>
  <% end %>
  <div id="testsubmitbutton">Submit</div>
<% end %>

<span id="scantronid"><%= @scantron.id %></span>

<% if @answers %>
  <h2>You scored <%= @scantron.convert_to_percent %> on this test.</h2>
  <% @answers.each_with_index do |answer, index| %>
    <h3><%= index + 1 %>) <%= answer.question.content %></h3>
    <% answer.question.choices.each do |choice| %>
      <% if answer.choice_id == choice.id %>
        <% answer.correct ? answered_class = "results-container is-correct" : answered_class = "results-container is-incorrect" %>
      <% else %>
        <% choice.correct ? answered_class = "results-container is-correct" : answered_class = "results-container" %>
      <% end %>
      <div class="<%= answered_class %>">
        <%= choice.content %>
      </div>
    <% end %>
  <% end %>
<% end %>

<br>
<br>
<%= link_to "Back to Cohort Page", cohort_path(params[:cohort_id]) %>