config/routes.rb
Rails.application.routes.draw do
  get 'about/index'

  root 'welcome#index'

  resources :welcome, only: [:create]
  resources :user_sessions

  resources :drivers do
    resources :appointments
  end

  resources :users do
    resources :appointments
    resources :grades, only: [:create]
  end
  resources :cohorts do
    resources :exams
  end

  resources :questions
  resources :attacheds, only: [:create, :destroy]
  resources :answers
  resources :scantrons, only: [:create, :update]

  get 'redlight' => 'games#redlight', :as => :redlight
  get 'login' => 'user_sessions#new', :as => :login
  get 'logout' => 'user_sessions#destroy', :as => :logout

end

app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController
  skip_before_action :require_login, except: [:destroy]

  def new
    @user = User.new
  end


  def create
    if @user = login(params[:email], params[:password])
    redirect_to user_path(current_user.id), notice: 'Login successful'
    else
      flash.now[:alert] = 'Login failed'
      render action: 'new'
    end
  end

  def destroy
    logout
    redirect_to root_path, notice: 'Logged out!'
  end
end

app/helpers/user_sessions_helper.rb
module UserSessionsHelper
end

app/views/user_sessions/_form.html.erb
<%= form_tag user_sessions_path, :method => :post do %>
  <div class="field">
    <%= label_tag :email %><br />
    <%= text_field_tag :email %>
  </div>
  <div class="field">
    <%= label_tag :password %><br />
    <%= password_field_tag :password %>
  </div>

  <div class="actions">
    <%= submit_tag "Login" %>
  </div>
<% end %>

app/views/user_sessions/create.html.erb
<h1>UserSessions#create</h1>
<p>Find me in app/views/user_sessions/create.html.erb</p>

app/views/user_sessions/destroy.html.erb
<h1>UserSessions#destroy</h1>
<p>Find me in app/views/user_sessions/destroy.html.erb</p>

app/views/user_sessions/new.html.erb
<h1>Login</h1>

<%= render 'form' %>

<%= link_to 'Back', user_sessions_path %>