config/routes.rb
Rails.application.routes.draw do
  get 'about/index'

  root 'welcome#index'

  resources :welcome, only: [:create]
  resources :user_sessions

  resources :drivers do
    resources :appointments
  end

  resources :users do
    resources :appointments
    resources :grades, only: [:create]
  end
  resources :cohorts do
    resources :exams
  end

  resources :questions
  resources :attacheds, only: [:create, :destroy]
  resources :answers
  resources :scantrons, only: [:create, :update]

  get 'redlight' => 'games#redlight', :as => :redlight
  get 'login' => 'user_sessions#new', :as => :login
  get 'logout' => 'user_sessions#destroy', :as => :logout

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)

    user ||= User.new

    if user.role == "admin"
      can :manage, :all

    elsif user.role == "student"
      can :read, Appointment
      can :create, Appointment
      can :update, Appointment do |appointment|
        appointment.try(:user) == user
      end
    elsif user.role == "driving_instructor"
      can :manage, Appointment
    end
  end
end
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all

    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #

app/models/answer.rb
class Answer < ActiveRecord::Base
  validates :scantron_id, :presence => true
  validates :question_id, :presence => true
  validates :correct, :presence => true
  validates :choice_id, :presence => true

  belongs_to :scantron
  belongs_to :question

end

app/models/appointment.rb
class Appointment < ActiveRecord::Base
  belongs_to :user
  belongs_to :driver


  def astart_time
    astart_time = start_time.strftime("%I:%M %p")
  end

  def aend_time
    aend_time = end_time.strftime("%I:%M %p")
  end
  

end

app/models/attached.rb
class Attached < ActiveRecord::Base
  belongs_to :exam
  belongs_to :question

end

app/models/category.rb
class Category < ActiveRecord::Base
  validates :name, :presence => true,
                   :uniqueness => true
                   
  has_many :questions

end

app/models/choice.rb
class Choice < ActiveRecord::Base
  validates :content, :presence => true,
                      :length => {minimum: 1},
                      :length => {maximum: 200}

  belongs_to :question
end

app/models/cohort.rb
class Cohort < ActiveRecord::Base
  validates :name, :presence => true
  validates :start_date, :presence => true
  validates :end_date, :presence => true

  has_many :exams
  has_many :users

  def end_display
    mytime = self.end_date
    mytime.strftime("%B %-d, %Y")
  end

  def start_display
    mytime = self.start_date
    mytime.strftime("%B %-d, %Y")
  end

  def self.get_cohort_by_exam(exam)
    Cohort.where(id: exam.cohort_id).first
  end
end

app/models/driver.rb
class Driver < ActiveRecord::Base
  has_many :appointments
  has_many :users, through: :appointments

  geocoded_by :address
  after_validation :geocode

  mount_uploader :avatar, AvatarUploader

end

app/models/exam.rb
class Exam < ActiveRecord::Base
  validates :name, :presence => true
  validates :cohort_id, :presence => true

  belongs_to :cohort
  has_many :attacheds
  has_many :questions, :through => :attacheds
  has_many :scantrons

  def average_grade
    if self.scantron.any?
      total_score = 0
      total_questions = 0
      running_score = []

      self.scantrons.each do |scantron|
        if scantron.answers.any?
          scantron.answers.each do |answer|
            total_questions += 1
            if answer.correct == true
              total_score += 1
            end
          end
        running_score << total_score/total_questions
        end
      end

      running_score != 0 ? "#{((running_score.sum / running_score.length)*100)}%" : ""
    end
  end

  def self.get_exam_by_scantron(scantron)
    Exam.where(id: scantron.exam_id).first
  end

end

app/models/game.rb
class Game < ActiveRecord::Base

def self.get_class_for_game_result(scantrons, current_user_id)
  if scantrons.where(game_name: 'redlight').where(user_id: current_user_id).first
    scantron = scantrons.where(game_name: 'redlight').where(user_id: current_user.id).first
    if scantron.result == 1.0
      return "cohorts-exam-list-passed"
    else
      return "cohorts-exam-list-failed"
    end
  end
end

end

app/models/question.rb
class Question < ActiveRecord::Base
  validates :content, :presence => true,
                      :length => {minimum: 3},
                      :length => {maximum: 200}

  has_many :choices
  has_many :attacheds
  has_many :exams, :through => :attacheds
  belongs_to :category

  accepts_nested_attributes_for :choices, reject_if: :all_blank, allow_destroy: true

  # gets all the answers by an active record collection for a specific question
  def answers_for_a_question
    @answers = if Answer.where(question_id: self.id)
      Answer.where(question_id: self.id)
    else
      []
    end
  end

  def self.average_difficulty_of_question(answers)
    return 0.25 if answers == []

    answer_counter = 0;
    correct_counter = 0;
    correct_array = []

    answers.each do |answer|
      answer_counter += 1
      correct_counter += 1 if answer.correct
    end

    correct_counter/answer_counter.round(3)
  end

  def self.number_of_stars(difficulty_rating)
    difficulty_rating *= 100
    return case difficulty_rating
    when 90..100 then 1
    when 75..89 then 2
    when 60..74 then 3
    when 30..59 then 4
    when 0..29 then 5
    else 0
    end
  end

end

app/models/scantron.rb
class Scantron < ActiveRecord::Base
  validates :user_id, :presence => true

  has_many :answers
  belongs_to :exam
  belongs_to :user

  def convert_to_percent
    (self.result*100).round(2)
  end

  def self.find_scantron_by_exam(exam_id, user_id)
    Scantron.where(exam_id: exam_id).where(user_id: user_id).first
  end

  def self.class_for_scantron(exam_id, user_id)
    scantron_class = ""
    if Scantron.find_scantron_by_exam(exam_id, user_id)
      scantron_current = Scantron.find_scantron_by_exam(exam_id, user_id)
      if scantron_current.result != nil
        scantron_current.result > 0.75 ? scantron_class = "cohorts-exam-list-passed" : scantron_class = "cohorts-exam-list-failed"
      else
        return false
      end
    else
      return false
    end

    scantron_class
  end

  def self.any_test_complete?(user_id)
    Scantron.where(user_id: user_id).where.not('result' => nil).first
  end

  def self.get_scantrons_with_game_finished
    Scantron.where.not('game_name' => nil).where.not('result' => nil)
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :appointments
  has_many :scantrons
  has_many :drivers, through: :appointments
  belongs_to :cohort
  authenticates_with_sorcery!

  validates :password, length: { minimum: 3 }, if: -> { new_record? || changes["password"] }
  validates :password, confirmation: true, if: -> { new_record? || changes["password"] }
  validates :password_confirmation, presence: true, if: -> { new_record? || changes["password"] }

  validates :email, uniqueness: true

  ROLES = %i[admin student driving_instructor]

  def self.instructor_id(name)
    u = User.where(name: name).first
    u.id
  end

  def completed_any_test?
    Scantron.any_test_complete?(self.id)
  end

  def self.any_user_completed_test?
    User.all.each { |user|
      return true if Scantron.any_test_complete?(user.id)
    }
    return false
  end

end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/choices_helper.rb
module ChoicesHelper
end

app/helpers/driver_helper.rb
module DriverHelper
end

app/helpers/exams_helper.rb
module ExamsHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.erb
<div class="container">
  <footer class="footer">
    <small>
    </small>
    <nav>

    </nav>
  </footer>
</div>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>

      <%= link_to "DRIVEXUS", root_path, class: "navbar-brand", id: "logo" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <!-- <li class><a href="#">Link <span class="sr-only">(current)</span></a></li> -->
        <!-- <li><a href="#">SignUp</a></li> -->
        <!-- <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">Separated link</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">One more separated link</a></li>
          </ul>
        </li> -->
      </ul>
      <!-- <form class="navbar-form navbar-left" role="search">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div> -->
        <!-- <button type="submit" class="btn btn-default">Submit</button> -->
      </form>
      <ul class="nav navbar-nav navbar-right">
        <% if current_user %>
          <li><%= link_to "#{current_user.name} Profile", user_path(current_user) %></li>
          <li><%= link_to "Logout", logout_path(current_user) %></li>
        <% else %>
          <li><%= link_to "Sign Up", new_user_path %></li>
          <li><%= link_to "Login", login_path %></li>
        <% end %>
        <!-- <li><a href="#">Login</a></li> -->
        <!-- <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">Separated link</a></li>
          </ul>
        </li> -->
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/_pre_navbar.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>

      <%= link_to "DRIVEXUS", root_path, class: "navbar-brand", id: "logo" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <!-- <li class><a href="#">Link <span class="sr-only">(current)</span></a></li> -->
        <!-- <li><a href="#">SignUp</a></li> -->
        <!-- <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">Separated link</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">One more separated link</a></li>
          </ul>
        </li> -->
      </ul>
      <!-- <form class="navbar-form navbar-left" role="search">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div> -->
        <!-- <button type="submit" class="btn btn-default">Submit</button> -->
      </form>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "SignUp", new_user_path %></li>
        <li><%= link_to "Login", login_path %></li>
        <!-- <li><a href="#">Login</a></li> -->
        <!-- <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">Separated link</a></li>
          </ul>
        </li> -->
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Drivexus</title>
     <link rel="stylesheet" href"stylesheets/animate.css">
      <%= stylesheet_link_tag    "application" %>
      <%= javascript_include_tag "application" %>
      <%= javascript_include_tag "https://maps.googleapis.com/maps/api/js?key=#{ENV['google_maps_api_key']}&callback=initMap", asnyc: true, defer: true%>
      <%= csrf_meta_tags %>
  </head>
  <body>

  <!-- <div id="nav">
    <% if current_user %>
      <%= link_to "Edit Profile", edit_user_path(current_user.id) %>
      <%= link_to "Logout", :logout, method: :post %>
    <% else %>
      <%= link_to "Register", new_user_path %> |
      <%= link_to "Login", :login %> -->
    <!-- <% end %>
  </div> -->
  <div slideInDown animated>
    <p id="notice"><%= flash[:notice] %></p>
    <p id="alert"><%= flash[:alert] %></p>
    <%= render 'layouts/navigation' %>
  </div>
  <div class="container">
  <%= yield %>
  </div>

  </body>
  <div>
  <%= render 'layouts/footer' %>
</div>
</html>